FROM @BASE_IMAGE_NAME@
LABEL maintainer="CMS Build"
LABEL name="CMS Worker Node on EL - Grid packages"

RUN dnf install -y xrootd-client openldap-compat &&\
    dnf install -y @EPEL_PACKAGES@ myproxy &&\
    xcmd="@EXTRA_COMMAND@" &&\
    if [ "$xcmd" = "" ] ; then xcmd=true; fi &&\
    eval $xcmd &&\
    /root/fix_ssh_config.sh /etc/ssh/ssh_config &&\
    echo "Timestamp: @BUILD_DATE@" > /image-build-info.txt

LABEL build-date="@BUILD_DATE@"
