FROM cmssw/slc7-builder:v20
USER root
RUN yum install -y  python-pip
RUN pip install --upgrade pip
RUN mkdir -p /opt/py2-packages
RUN pip install -t /opt/py2-packages pyyaml
RUN pip install -t /opt/py2-packages PyGithub requests
RUN chown -R cmsbuild /opt/py2-packages/*
env PYTHONPATH /opt/py2-packages
USER cmsbuild
