FROM cmssw/slc7-builder:v20
USER root
RUN yum install -y  python-pip
RUN pip install --upgrade pip
RUN mkdir -p /home/cmsbuild/packages
RUN pip install -t /home/cmsbuild/packages PyGithub
RUN chown -R cmsbuild /home/cmsbuild/packages/*
env PYTHONPATH /home/cmsbuild/packages
USER cmsbuild

