FROM @BASE_IMAGE_NAME@

RUN yum install -y \
        java-1.8.0-openjdk python-pip python-devel java-1.8.0-openjdk-devel ntp \
        git subversion bc finger zip unzip which bzip2 \
        glibc coreutils bash tcsh zsh perl tcl tk readline openssl ncurses e2fsprogs krb5-libs freetype fontconfig \
        libstdc++ libidn libX11 libXmu libSM libICE libXcursor libXext libXrandr libXft mesa-libGLU mesa-libGL \
        e2fsprogs-libs libXi libXinerama libXrender libXpm gcc-c++ libcom_err libXpm-devel libXft-devel libX11-devel \
        libXext-devel mesa-libGLU mesa-libGLU-devel libGLEW glew perl-Digest-MD5 perl-ExtUtils-MakeMaker patch \
        perl-libwww-perl krb5-libs krb5-devel perl-Data-Dumper perl-WWW-Curl texinfo hostname time perl-Carp \
        perl-Text-ParseWords perl-PathTools perl-ExtUtils-MakeMaker perl-Exporter perl-File-Path perl-Getopt-Long \
        perl-constant perl-File-Temp perl-Socket perl-Time-Local perl-Storable glibc-headers perl-threads \
        perl-Thread-Queue perl-Module-ScanDeps perl-Test-Harness perl-Env perl-Switch perl-ExtUtils-Embed \
        ncurses-libs perl-libs file wget lcg-CA perl-LWP-Protocol-https fetch-crl python-setuptools \
        setroubleshoot-server autofs gdb attr python-requests-kerberos libgfortran time python2-psutil &&\
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y voms-clients-cpp krb5-workstation myproxy &&\
    yum clean all

ADD krb5.conf /etc/krb5.conf
RUN mkdir -p /cvmfs /afs /eos /etc/vomses /etc/grid-security /data /pool /build &&\
    touch /etc/tnsnames.ora
WORKDIR /build
