FROM @BASE_IMAGE_NAME@

ADD http://linux.web.cern.ch/linux/centos7/CentOS-CERN.repo           /etc/yum.repos.d/CentOS-CERN.repo
ADD http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern /etc/pki/rpm-gpg/RPM-GPG-KEY-cern
RUN yum install -y yum-plugin-ovl git-core glibc-devel \
        openssl openssl-devel openssl-libs \
        pciutils glx-utils mesa-dri-drivers libX11 libXi libXrender \
        mesa-libGL-devel mesa-libGLU-devel libXext-devel \
        tcsh zsh tcl tk e2fsprogs perl-ExtUtils-Embed compat-libstdc++-33 libXmu e2fsprogs-libs libXpm bc libaio \
        tar patch krb5-devel perl-Data-Dumper gcc unzip zip perl-libwww-perl libXpm-devel libXft-devel svn cvs \
        gcc-c++ strace cern-wrappers  wget hostname readline-devel nano bzip2 perl-Switch perl-Storable \
        perl-Env perl-Thread-Queue CERN-CA-certs tk-devel tcl-devel which file \
        java-1.8.0-openjdk java-1.8.0-openjdk-devel popt libXcursor libXrandr libXinerama nspr nss nss-util file file-libs \
        readline popt bzip2 bzip2-libs python-requests-kerberos libgfortran time python3 && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y voms-clients-cpp krb5-workstation myproxy python2-psutil python2-pip python3-pip singularity &&\
    yum clean all

ADD krb5.conf /etc/krb5.conf
ADD psutil.patch /tmp/psutil.patch
RUN mkdir -p /cvmfs /afs /eos /etc/vomses /etc/grid-security /data /pool /build &&\
    touch /etc/tnsnames.ora &&\
    patch -p0 < /tmp/psutil.patch &&\
    sed -i -e s'|^ *allow  *setuid.*|allow setuid = no|;s|^ *enable  *overlay.*|enable overlay = no|;s|^ *enable  *underlay.*|enable underlay = yes|' /etc/singularity/singularity.conf
WORKDIR /build
RUN yum install -y doxygen && yum clean all
