FROM @BASE_IMAGE_NAME@

ADD http://linux.web.cern.ch/linux/centos7/CentOS-CERN.repo           /etc/yum.repos.d/CentOS-CERN.repo
ADD http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern /etc/pki/rpm-gpg/RPM-GPG-KEY-cern
RUN yum install -y yum-plugin-ovl HEP_OSlibs_CC7 git-core openssl glibc-devel \
        pciutils glx-utils mesa-dri-drivers libX11 libXi libXrender \
        mesa-libGL-devel mesa-libGLU-devel libXext-devel \
        tcsh zsh tcl tk e2fsprogs perl-ExtUtils-Embed compat-libstdc++-33 libXmu e2fsprogs-libs libXpm bc libaio \
        tar patch krb5-devel perl-Data-Dumper gcc unzip zip perl-libwww-perl libXpm-devel libXft-devel svn cvs \
        gcc-c++ strace cern-wrappers krb5-workstation wget hostname readline-devel nano bzip2 perl-Switch perl-Storable \
        perl-Env packages perl-Thread-Queue CERN-CA-certs tk-devel tcl-devel which python-pip file voms-clients-cpp myproxy \
        java-1.8.0-openjdk java-1.8.0-openjdk-devel popt libXcursor libXrandr libXinerama nspr nss nss-util file file-libs \
        readline popt bzip2 bzip2-libs python-requests-kerberos libgfortran time python2-psutil && \
    yum clean all

ADD krb5.conf /etc/krb5.conf
RUN mkdir -p /cvmfs /afs /eos /etc/vomses /etc/grid-security /data /pool /build &&\
    touch /etc/tnsnames.ora
WORKDIR /build

