FROM @BASE_IMAGE_NAME@
RUN dnf install -y bzip2-devel file popt-devel nspr-devel nss-devel \
        rpm-build autoconf automake libtool gettext-devel \
        python3-devel cmake bison && \
    dnf clean all && rm -rf /var/cache/yum /var/cache/dnf
