FROM @BASE_IMAGE_NAME@
LABEL maintainer="CMS Build"
LABEL name="CMS Worker Node on EL - Runtime"

ADD CERN.repo               /tmp/CERN.repo
ADD RPM-GPG-KEY-kojiv2      /tmp/RPM-GPG-KEY-kojiv2
ADD fix_ssh_config.sh       /tmp/fix_ssh_config.sh

RUN dnf install -y @DEFAULT_PACKAGES@ bash tcsh zsh tar glibc glibc-headers libxcrypt openssl-libs libcom_err krb5-libs ncurses-libs \
          perl perl-libs libX11 readline tcl tk mesa-libGLU libglvnd-glx libglvnd-opengl libXext libXft libXpm libaio libnsl &&\
    dnf install -y python3 which procps-ng &&\
    dnf install -y epel-release &&\
    dnf install -y @EPEL_PACKAGES@ voms-clients-cpp apptainer python3-requests python3-psutil python3-pip  &&\
    xcmd="@EXTRA_COMMAND@" &&\
    if [ "$xcmd" = "" ] ; then xcmd=true; fi &&\
    eval $xcmd &&\
    echo el9 > /etc/cmsos &&\
    cp /tmp/CERN.repo /etc/yum.repos.d/CERN.repo &&\
    rpm --import /tmp/RPM-GPG-KEY-kojiv2 &&\
    dnf install -y cern-gpg-keys CERN-CA-certs &&\
    update-ca-trust &&\
    dnf update -y ca-certificates &&\
    dnf clean all &&\
    mkdir -p /cvmfs /afs /eos /etc/vomses /etc/grid-security /build /data /pool /opt/cms /etc/ssh &&\
    mkdir -p /hdfs /mnt/hadoop /hadoop /cms /etc/cvmfs/SITECONF /lfs_roots /storage &&\
    touch /etc/tnsnames.ora &&\
    /tmp/fix_ssh_config.sh /etc/ssh/ssh_config &&\
    rm -f /tmp/CERN.repo /tmp/RPM-GPG-KEY-kojiv2 /tmp/fix_ssh_config.sh &&\
    echo "Timestamp: @BUILD_DATE@"   > /image-build-info.txt &&\
    sed -i -e s'|^ *allow  *setuid.*|allow setuid = no|;s|^ *enable  *overlay.*|enable overlay = no|;s|^ *enable  *underlay.*|enable underlay = yes|' /etc/apptainer/apptainer.conf

LABEL build-date="@BUILD_DATE@"
