FROM @BASE_IMAGE_NAME@
RUN yum install -y bzip2-devel file popt-devel nspr-devel nss-devel \
        rpm-build autoconf automake libtool gettext-devel \
        python3-devel cmake bison bison-devel && \
    yum clean all
