FROM cmssw/slc6-base

USER    cmsinst
WORKDIR /opt/cms
RUN     wget -O /opt/cms/bootstrap.sh http://cmsrep.cern.ch/cmssw/repos/bootstrap.sh
RUN     sh /opt/cms/bootstrap.sh setup -r cms -architecture @ARCH@ -server cmsrep.cern.ch 
RUN     /opt/cms/common/cmspkg -a @ARCH@ install -y cms+local-cern-siteconf+sm111124
RUN     /opt/cms/common/cmspkg -a @ARCH@ install -y @CMS_PACKAGE@
RUN     /opt/cms/common/cmspkg -a @ARCH@ clean

USER    root
RUN     /bin/cp -f /opt/cms/cmsset_default.sh  /etc/profile.d/
RUN     /bin/cp -f /opt/cms/cmsset_default.csh /etc/profile.d/
USER    cmsbld
