FROM docker.io/cmssw/fc39:riscv64
RUN dnf5 install -y bzip2-devel file popt-devel nspr-devel nss-devel \
        rpm-build autoconf automake libtool gettext-devel \
        python3-devel cmake bison && \
    dnf5 clean all
