FROM @BASE_IMAGE_NAME@
LABEL maintainer="CMS Build"
LABEL name="CMS Worker Node on EL - User packages"

RUN dnf install -y man-db time bc nano strace perf xauth vim xrootd-client &&\
    epel_pkgs="@EPEL_PACKAGES@" &&\
    if [ -n "$epel_pkgs" ] ; then dnf install -y $epel_pkgs; fi &&\
    xcmd="@EXTRA_COMMAND@" &&\
    if [ "$xcmd" = "" ] ; then xcmd=true; fi &&\
    eval $xcmd &&\
    echo "Timestamp: @BUILD_DATE@" > /image-build-info.txt

LABEL build-date="@BUILD_DATE@"
