FROM @BASE_IMAGE_NAME@
LABEL maintainer="CMS Build"
LABEL name="CMS Worker Node on EL - Grid packages"

ADD https://raw.githubusercontent.com/fermitools/htgettoken/e7d1d46528566d9e43120ac83153894054d75ad1/htdecodetoken /usr/bin/

RUN chmod +x /usr/bin/htdecodetoken &&\
	dnf --enablerepo=powertools install -y boost-python3 &&\
	dnf install -y gfal2-util-scripts gfal2-all python3-gfal2-util xrootd-client &&\
	dnf install -y @EPEL_PACKAGES@ myproxy &&\
	xcmd="@EXTRA_COMMAND@" &&\
	if [ "$xcmd" = "" ] ; then xcmd=true; fi &&\
	eval $xcmd &&\
	dnf clean all &&\
	/root/fix_ssh_config.sh /etc/ssh/ssh_config &&\
	echo "Timestamp: @BUILD_DATE@" > /image-build-info.txt
	
LABEL build-date="@BUILD_DATE@"
