FROM @BASE_IMAGE_NAME@
LABEL maintainer="CMS Build"
LABEL name="CMS Worker Node on EL - Grid packages"

RUN dnf --enablerepo=powertools install -y boost-python3
RUN dnf install -y gfal2-util-scripts gfal2-all python3-gfal2-util &&\ 
    epel_pkgs="@EPEL_PACKAGES@" &&\
    if [ -n "$epel_pkgs" ] ; then dnf install -y $epel_pkgs; fi &&\
    xcmd="@EXTRA_COMMAND@" &&\
    if [ "$xcmd" = "" ] ; then xcmd=true; fi &&\
    eval $xcmd &&\
    echo "Timestamp: @BUILD_DATE@" > /image-build-info.txt

LABEL build-date="@BUILD_DATE@"
